spring.datasource.url=jdbc:postgresql://localhost:5432/empay_hrms
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mail config - replace with your SMTP credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nihar.mehakare24@vit.edu
spring.mail.password=ngipggkmpznnwrej
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin default credentials (seeded on startup)
app.admin.email=admin@empay.com
app.admin.password=Admin@123
