spring.datasource.url=jdbc:h2:mem:empaydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Mail config - replace with your SMTP credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nihar.mehakare24@vit.edu
spring.mail.password=ngipggkmpznnwrej
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin default credentials (seeded on startup)
app.admin.email=admin@empay.com
app.admin.password=Admin@123
